services:
  mysql:
    image: mysql
    container_name: backend-db
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: